version: "3"

services:
  gogs:
    image: gogs/gogs:0.11.34
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - "./data/gogs:/data"

  drone-server:
    image: drone/drone:0.8
    ports:
      - "8000:8000"
      - "9000"
    volumes:
      - "./data/drone:/var/lib/drone/"
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://$DOMAIN_NAME:8000
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://$DOMAIN_NAME:10080
      - DRONE_SECRET=mysecret
      - DRONE_ADMIN=$ADMIN_USERS

  drone-agent:
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=mysecret

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "./data/registry/:/var/lib/registry"
